### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by cionoiu** [sydcode/custom_attributes#2]
I GET THE NEXT

Fatal error: Uncaught exception 'Exception' with message '1074 - Column length too big for column 's_options' (max = 21845); use BLOB or TEXT instead' in /home/admin/domains/MY_DOMAIN/public_html/oc-content/plugins/custom_attributes/attributes.php:780 Stack trace: #0 /home/admin/domains/MY_DOMAIN/public_html/oc-content/plugins/custom_attributes/attributes.php(64): Attributes->import('custom_attribut...') #1 /home/admin/domains/MY_DOMAIN/public_html/oc-content/plugins/custom_attributes/index.php(54): Attributes->updateDatabase() #2 /home/admin/domains/MY_DOMAIN/public_html/oc-content/plugins/custom_attributes/index.php(63): CustomAttributes->__construct() #3 /home/admin/domains/MY_DOMAIN/public_html/oc-content/plugins/custom_attributes/index.php(469): CustomAttributes::newInstance() #4 /home/admin/domains/MY_DOMAIN/public_html/oc-admin/plugins.php(248): include('/home/admin/dom...') #5 /home/admin/domains/MY_DOMAIN/public_html/oc-admin/index.php(80): CAdminPlugins->do in /home/admin/domains/MY_DOMAIN/public_html/oc-content/plugins/custom_attributes/attributes.php on line 780

WHAT TO DO?

**Comment by srbijaoglasi** [comment]
Hello,did you resolve this issue i have the same problem?  Tnx.
